INSERT INTO RATING (RATING_ID,  RATING_NAME)
VALUES (1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, 'R'),(5, 'NC-17');

INSERT INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (1, 'COMEDY'), (2, 'DRAMA'), (3, 'CARTOON'), (4, 'THRILLER'), (5, 'DOCUMENTARY'), (6, 'ACTION_MOVIE');

INSERT INTO FRIENDSHIP (FRIENDSHIP_ID, FRIENDSHIP_STATUS)
VALUES (0, 'Не подтверждён'),
       (1, 'Подтверждён');
